USE [master]
GO

/****** Object:  Database [ReShopDB]    Script Date: 8/1/2021 12:45:05 AM ******/
DROP DATABASE [ReShopDB]
GO

/****** Object:  Database [ReShopDB]    Script Date: 8/1/2021 12:45:05 AM ******/
CREATE DATABASE [ReShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\ReShopDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ReShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\ReShopDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ReShopDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReShopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReShopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReShopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReShopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReShopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReShopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReShopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReShopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReShopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReShopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReShopDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReShopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReShopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReShopDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ReShopDB] SET  MULTI_USER 
GO

ALTER DATABASE [ReShopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReShopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReShopDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ReShopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ReShopDB] SET  READ_WRITE 
GO


